import { Metadata } from "next";

export default function Home() {
  return <main></main>;
}

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
